services:
  app:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - dump-data:/usr/src/app/dump
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  dump-data:
